# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 build-vite-plugin:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory:  ./packages/vite-plugin-yext-sites-ssg
    strategy:
      matrix:
        node-version: [16.x, 17.x]
    steps:
    - uses: actions/checkout@v3
    - name: "@yext/vite-plugin-yext-sites-ssg: build with node ${{ matrix.node-version }}"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run types

 build-yext-sites-scripts:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory:  ./packages/yext-sites-scripts
    strategy:
      matrix:
        node-version: [16.x, 17.x]
    steps:
    - uses: actions/checkout@v3
    - name: "@yext/yext-sites-scripts: build with node ${{ matrix.node-version }}"
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run types